<a href="https://colab.research.google.com/github/Tahan402/DailyPractice/blob/main/Lecture_8_Using_arrays_and_Scalars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
from __future__ import division

In [7]:
5/2

2.5

In [9]:
arr1= np.array([[1,2,3,4],[8,9,10,11]])

In [10]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [11]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [13]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [15]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])