<a href="https://colab.research.google.com/github/Tahan402/DailyPractice/blob/main/Lecture_11_Universal_Array_Functions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
 A = np.random.randn(10)
 A

array([-0.16251824,  0.54588505, -0.58791391, -0.15503685, -1.32122198,
       -0.42210079, -0.49646262,  2.02134771,  1.87437627, -1.29022375])

In [7]:
B = np.random.randn(10)
B

array([-0.69324583, -0.00302203,  0.07141957,  0.20097801, -0.36396592,
       -1.32923776, -0.23654656,  1.32949701,  0.23013139,  0.43185276])

In [9]:
#Binary Function
np.add(A,B)

array([-0.85576407,  0.54286302, -0.51649434,  0.04594116, -1.6851879 ,
       -1.75133855, -0.73300918,  3.35084472,  2.10450766, -0.85837099])

In [10]:
np.maximum(A,B)

array([-0.16251824,  0.54588505,  0.07141957,  0.20097801, -0.36396592,
       -0.42210079, -0.23654656,  2.02134771,  1.87437627,  0.43185276])

In [11]:
np.minimum(A,B)

array([-0.69324583, -0.00302203, -0.58791391, -0.15503685, -1.32122198,
       -1.32923776, -0.49646262,  1.32949701,  0.23013139, -1.29022375])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

False