<a href="https://colab.research.google.com/github/Tahan402/DailyPractice/blob/main/Lecture_41_Permutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd

In [2]:
dframe = pd.DataFrame(np.arange(16).reshape(4,4))

In [3]:
blender = np.random.permutation(4)

In [4]:
blender

array([3, 0, 1, 2])

What is NP random permutation?


Random Permutations of Elements

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa

In [5]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
dframe.take(blender)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

In [7]:
box  = np.array([1,2,3])

In [8]:
shaker = np.random.randint(0,len(box),size = 10)

In [9]:
shaker

array([0, 2, 0, 0, 0, 1, 0, 1, 2, 0])

In [10]:
hand_grabs = box.take(shaker)

In [11]:
hand_grabs

array([1, 3, 1, 1, 1, 2, 1, 2, 3, 1])