<a href="https://colab.research.google.com/github/Tahan402/DailyPractice/blob/main/Lecture_31_Concatenate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = pd.Series([0,1,2],index= ['T','U','V'])

ser2 = pd.Series([3,4] , index = ['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = pd.DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = pd.DataFrame(np.random.randn(3,3),columns= ['Y','Q','X'])

In [13]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.830842  0.389204 -1.909243       NaN
1  0.468101  0.167219  2.025036       NaN
2  0.775040  1.287823  0.302038       NaN
3 -0.635725 -0.509509 -0.072410       NaN
0  0.933549  0.365520       NaN  0.435814
1 -2.208507  0.311807       NaN -1.019085
2  0.302253  2.049142       NaN -0.974813

In [15]:
pd.concat([dframe1,dframe2],ignore_index = True) # make index continuous

X         Y         Z         Q
0 -0.830842  0.389204 -1.909243       NaN
1  0.468101  0.167219  2.025036       NaN
2  0.775040  1.287823  0.302038       NaN
3 -0.635725 -0.509509 -0.072410       NaN
4  0.933549  0.365520       NaN  0.435814
5 -2.208507  0.311807       NaN -1.019085
6  0.302253  2.049142       NaN -0.974813